# Generated by Django 5.1.7 on 2025-03-29 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorylog_supplier_inventoryitemsupplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, help_text='Warehouse location', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitemsupplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='new_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='previous_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='quantity_change',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
