# Generated by Django 5.1.7 on 2025-03-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_location_inventoryitem_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemsupplier',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
