# Generated by Django 5.1.7 on 2025-04-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitemsupplier_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Minimum stock level before alert'),
        ),
    ]
